language: python
python: "3.5"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
install:
  - pip install -r requirements.txt
  - pip install tox coveralls --use-mirrors
script: tox
after_success:
  if [ "$TOXENV" == "py27" ]; then coveralls; fi
