language: python
python: "2.7"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
install:
  - pip install -r requirements.txt
  - pip install tox coveralls
script:
  - ./tool/test-ci.sh
after_success:
  if [ "$TOXENV" == "py27" ]; then coveralls; fi
  - bash <(curl -s https://codecov.io/bash)
